In [ ]:
import numpy as np
np.random.randn(3,2)

In [2]:
s_array=np.arange(30)
s_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.rand(3,2)

array([[0.26853822, 0.76416396],
       [0.73813888, 0.40661823],
       [0.45873073, 0.14407486]])

In [7]:
np.random.randn(3,2)

array([[ 0.51168565, -1.75685433],
       [ 0.28538137,  1.17378757],
       [ 0.34379539,  0.66776395]])

In [8]:
np.random.randint(1,5)

2

In [11]:
r=np.random.randint(0,100,20)
r

array([89,  5,  7, 53, 28, 34, 32, 27, 10, 36, 29, 12, 62, 20, 44, 26, 33,
       70, 64, 42])

In [13]:
s_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [14]:
r.min()

5

In [15]:
r.argmin()

1

In [16]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
a=np.random.rand(2,3)
a

array([[0.60148735, 0.75540476, 0.01597725],
       [0.95798421, 0.71462769, 0.83323568]])

In [19]:
a.T

array([[0.60148735, 0.95798421],
       [0.75540476, 0.71462769],
       [0.01597725, 0.83323568]])

In [21]:
s_array=np.arange(10,21)
s_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
s_array[3]

13

In [23]:
s_array[3:7]

array([13, 14, 15, 16])

In [ ]:
#Multidimensional array

In [24]:
sample=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [25]:
sample[0:2,2]

array([ 1, 21])

In [31]:
sample[:,3]

array([23, 33,  7])

In [32]:
sample[2,:]

array([56, 76, 24,  7])

In [33]:
sample[2]

array([56, 76, 24,  7])

In [35]:
sample[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [37]:
sample=np.arange(1,20)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [38]:
sample+sample

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [39]:
np.exp(sample)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [40]:
np.sqrt(sample)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [41]:
np.min(sample)

1

In [42]:
np.max(sample)

19

In [43]:
np.log(sample)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [44]:
np.argmax(sample)

18

In [45]:
np.argmin(sample)

0

In [46]:
np.square(sample)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [47]:
np.std(sample)

5.477225575051661

In [48]:
np.var(sample)

30.0

In [49]:
np.mean(sample)

10.0

In [50]:
array=np.random.randn(3,4)
array

array([[-0.38309004, -0.75700691, -0.52583427, -0.09880534],
       [-0.01326694,  0.29235628,  1.21844792, -0.74819967],
       [-1.37082925,  0.11777004, -1.04230553,  0.08883723]])

In [51]:
np.round(array,decimals=3)

array([[-0.383, -0.757, -0.526, -0.099],
       [-0.013,  0.292,  1.218, -0.748],
       [-1.371,  0.118, -1.042,  0.089]])

In [53]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')